[package]
name = "dosisod/matcha9000"
version = "1.0.2"
description = "A puzzle game for programmers"
readme = "README.md"
repository = "https://github.com/dosisod/matcha9000"
license = "GPL-3.0"

[[module]]
name = "matcha9000"
source = "matcha9000.wasm"
abi = "wasm4"
interfaces = { wasm4 = "0.0.1" }

[[command]]
runner = "wasm4@0.0.1"
name = "play"
module = "matcha9000"
